### ISSUE TITLE
Wont run on Arm

### ISSUE THREAD

**Issue by Tanariel** [lukechilds/docker-electrum-vertcoin#1]
Trying to run an electrum node but no luck so far : 

`jb@scw-56471d:~/docker-electrum-vertcoin$ sudo docker-compose up
[sudo] password for jb: 
Starting dockerelectrumvertcoin_vertcoind_1 ... 
Starting dockerelectrumvertcoin_vertcoind_1 ... done
Attaching to dockerelectrumvertcoin_electrumx_1, dockerelectrumvertcoin_vertcoind_1
electrumx_1  | standard_init_linux.go:185: exec user process caused "exec format error"
vertcoind_1  | standard_init_linux.go:185: exec user process caused "exec format error"
dockerelectrumvertcoin_electrumx_1 exited with code 1
dockerelectrumvertcoin_vertcoind_1 exited with code 1`

Running it on : 

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian

Arm64 computer.

Thanks in advance for your help :)

**Comment by lukechilds** [comment]
Hi, good on you for running a node!

Are you definitely using an up to date version of `docker`/`docker-compose`?

If so, are you able to run the ElectrumX and `vertcoind` images on their own or does that fail for you too?

**Comment by lukechilds** [comment]
Oh, sorry, just realised you're on Arm64, my prebuilt images are for x86. Everything should still work, you'll just need to manually build my docker images rather than pulling my prebuilt images in from docker hub.
